### ISSUE TITLE
Compilation | Build Issue

### ISSUE THREAD

**Issue by rootsid** [weak1337/Alcatraz#19]
I'm using these versions of asmjit and zydis

asmjit:x64-windows                                2023-03-25          Complete x86/x64 JIT and Remote Assembler for C++
zycore:x64-windows                                1.3.0#1             Provides platform independent types, macros and ...
zydis:x64-windows                                 4.0.0               Fast and lightweight x86/x86-64 disassembler lib...

I'm getting attached errors, please let me know if any version is wrong and suggest on following issue.

<img width="1629" alt="image" src="https://github.com/weak1337/Alcatraz/assets/14955716/2602dc6b-cde4-41f1-a19f-ca737ca300fc">

**Comment by piedacoulisse2** [comment]
Same as you i think there is a conflict with these lib.

**Comment by h4rmsw4y** [comment]
The has ZYDIS_ADDRESS_WIDTH_64 undeclared which is asked in this issue of zydis: https://github.com/zyantific/zydis/issues/258
Meaning it uses a version of zydis before this breaking change was merged: https://github.com/zyantific/zydis/pull/238

And vcpkg seems to just install the most recent version.

**Comment by weak1337** [comment]
I updated it to match the latest Zydis version
