### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by useragent23253** [weak1337/Alcatraz#2]
Is it possible to make 32 bit support?

**Comment by Malwaresupport** [comment]
Hi bro, please write to me in a telegram

**Comment by dev007new** [comment]
yes, interesting

**Comment by weak1337** [comment]
Hi, there is a 32bit mutation engine you can look at:
https://github.com/mike1k/perses.
If lots of people are still interested in 32bit I can add a small example but it won't feature all options 64bit has. I hope I can find some time for it after exam season.

**Comment by Malwaresupport** [comment]
Bro

**Comment by Malwaresupport** [comment]
@ENGASNAME Telegram

**Comment by Malwaresupport** [comment]
Please telegraph me
