### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by desire179** [weak1337/Alcatraz#20]
during the build process and the following error message appears:

Error	C1083	Cannot open include file: 'Zydis/Zydis.h': No such file or directory	Alcatraz-con	C:\Users\Senkin\Desktop\Alcatraz-master\Alcatraz\obfuscator\obfuscator.h	3	

I think I have successfully installed vcpkg repo via:
git clone https://github.com/Microsoft/vcpkg.git
.\vcpkg\bootstrap-vcpkg.bat
vcpkg install asmjit:x64-windows
vcpkg install zydis:x64-windows

how can i solve the problem with zydis??

**Comment by weak1337** [comment]
If you follow the linked tutorial:

vcpkg integrate install
Restart VS
Done

**Comment by desire179** [comment]
Great, succesfull
