### ISSUE TITLE
 Cannot open include file: 'Zydis/Zydis.h

### ISSUE THREAD

**Issue by DarknightCanada** [weak1337/Alcatraz#5]
I am following the instructions and doing this in the project folder:

Install: https://vcpkg.io/en/getting-started.html

asmjit: vcpkg.exe install asmjit:x64-windows
Zydis: vcpkg.exe install zydis:x64-windows

However when I try to compile I keep getting this error:

`Severity Code Description Project File Line Suppression State Error C1083 Cannot open include file: 'Zydis/Zydis.h': No such file or directory Alcatraz-gui C:\Users\darknight\Downloads\Alcatraz-master\Alcatraz-master\Alcatraz\obfuscator\obfuscator.h 3`

**Comment by weak1337** [comment]
Make sure you run the following command after installing both of these modules:
vcpkg integrate install

**Comment by DarknightCanada** [comment]
thanks
