### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by Sgamzat05** [weak1337/Alcatraz#6]
installed both packages but have this problem 
![image](https://user-images.githubusercontent.com/46753195/220187954-594d9086-157e-41d3-a207-9f147224b0c3.png)

**Comment by weak1337** [comment]
Use C++ 20

**Comment by Sgamzat05** [comment]
I'm stupid, sorry, I've already fixed it

**Comment by Sgamzat05** [comment]
![image](https://user-images.githubusercontent.com/46753195/220190204-19b22122-6649-4df4-a924-c5f7f89f8cfa.png)
Now this problem

**Comment by weak1337** [comment]
Compile as x64 release. These questions aren't project related

**Comment by Sgamzat05** [comment]
Will there be a different signature after each compilation of the protected sys file?

**Comment by Sgamzat05** [comment]
After each procedure, will anti-cheat perceive it as different drivers?
